[package]
name = "qstring"
description = "Query string parser"
version = "0.1.2"
authors = ["Martin Algesten <martin@algesten.se>"]
license = "MIT"
repository = "https://github.com/algesten/qstring"
readme = "README.md"
keywords      = [ "query", "url", "querystring" ]
exclude       = [
  ".gitignore",
]

[dependencies]
urlencoding = "1.0.0"
